language: node_js
node_js:
  - "7"
after_success:
  - npm run coveralls
  - test $TRAVIS_BRANCH = "master" && npm i -g now && npm run build && now out --static -n kebabstudios-web -t=$NOW_TOKEN --npm && now -t=$NOW_TOKEN alias